import { Vehicle, Order, DocumentItem, QuoteRequest, LeadItem } from '../types';

export const INITIAL_VEHICLES: Vehicle[] = [
  // ==========================================
  // 1. JETOUR LINEUP (China Direct / Transit)
  // ==========================================
  {
    id: 'jetour-t2-2025',
    slug: 'jetour-t2-traveller-2025-4wd',
    make: 'Jetour',
    model: 'T2 (Traveller)',
    year: 2025,
    badge: 'Conquest 4WD',
    vin: 'LVVDE41A6R0192831',
    priceToTema: 340000,
    pricingBreakdown: {
      vehicleAndShipping: 340000,
      estimatedCustoms: 75000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 428000,
    },
    availability: 'in_transit',
    origin: 'chinese_import',
    location: 'Vessel MSC LORETTO (En route to Tema)',
    etaWeeks: 'Arriving in 16 days',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 0,
    engine: '2.0T Kunpeng Turbo (254 HP)',
    driveType: '4WD',
    color: 'Sandstone Khaki',
    interiorColor: 'Desert Tan & Black Leather',
    seats: 5,
    images: [
      '/cars/jetour-t2.jpg',
      '/cars/jetour-t2-2.jpg',
      '/cars/jetour-t2-3.jpg',
      '/cars/jetour-t2-4.jpg',
      '/cars/jetour-t2-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema Port / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      'BorgWarner 6th-Gen Smart 4WD',
      'Sony 12-Speaker Sound System',
      '15.6-inch Central Control Display',
      'Snapdragon 8155 Automotive Chip',
      'Off-road Terrain Modes & Rock Crawl'
    ],
    description: 'The rugged, boxy off-road SUV currently taking Ghana by storm. High ground clearance, military-style aesthetics, and luxury interior tech.',
    isFeatured: true,
  },
  {
    id: 'jetour-dashing-2025',
    slug: 'jetour-dashing-15t-2025',
    make: 'Jetour',
    model: 'Dashing',
    year: 2025,
    badge: 'Deluxe Edition',
    vin: 'LVVDE41A6R0144910',
    priceToTema: 225000,
    pricingBreakdown: {
      vehicleAndShipping: 225000,
      estimatedCustoms: 51000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 289000,
    },
    availability: 'available_china',
    origin: 'chinese_import',
    location: 'Ningbo Export Logistics Hub, China',
    etaWeeks: '7-9 weeks to Tema Port',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 0,
    engine: '1.5T Turbocharged 4-Cylinder',
    driveType: 'FWD',
    color: 'Quantum Cyber Grey',
    interiorColor: 'Red & Black Sport',
    seats: 5,
    images: [
      '/cars/jetour-dashing.jpg',
      '/cars/jetour-dashing-2.jpg',
      '/cars/jetour-dashing-3.jpg',
      '/cars/jetour-dashing-4.jpg',
      '/cars/jetour-dashing-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema Port / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      'Futuristic Split Headlamp Design',
      'Concealed Pop-out Door Handles',
      'Panoramic Starry Sunroof',
      'Wireless Smartphone Fast Charging'
    ],
    description: 'Striking futuristic styling with ultra-low fuel consumption and cutting-edge digital cockpit technology.',
    isFeatured: false,
  },
  {
    id: 'jetour-x70-plus-2024',
    slug: 'jetour-x70-plus-7seater-2024',
    make: 'Jetour',
    model: 'X70 Plus',
    year: 2024,
    badge: 'Comfort 7-Seater',
    vin: 'LVVDE41A6R0188234',
    priceToTema: 245000,
    pricingBreakdown: {
      vehicleAndShipping: 245000,
      estimatedCustoms: 56000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 314000,
    },
    availability: 'available_china',
    origin: 'chinese_import',
    location: 'Shenzhen Shekou Port Depot, China',
    etaWeeks: '7-9 weeks to Tema Port',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 0,
    engine: '1.6T TGDI Engine (197 HP)',
    driveType: 'FWD',
    color: 'Glacier White',
    interiorColor: 'Brown Leather 7-Seats',
    seats: 7,
    images: [
      '/cars/jetour-x70.jpg',
      '/cars/jetour-x70-2.jpg',
      '/cars/jetour-x70-3.jpg',
      '/cars/jetour-x70-4.jpg',
      '/cars/jetour-x70-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema Port / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      '3-Row 7-Passenger Spacious Cabin',
      'Dual 10.25-inch Interconnected Screens',
      'Rear Air Conditioning Vents on all rows',
      'Roof Luggage Rails'
    ],
    description: 'Affordable luxury 7-passenger family and commercial executive SUV with strong Chery powertrain reliability.',
    isFeatured: false,
  },

  // ==========================================
  // 2. CHANGAN UNI SERIES (UNI-K, UNI-Z, UNI-V)
  // ==========================================
  {
    id: 'changan-unik-2025',
    slug: 'changan-uni-k-20t-awd-2025',
    make: 'Changan',
    model: 'UNI-K',
    year: 2025,
    badge: 'Flagship AWD',
    vin: 'LS5AB20D4R0081299',
    priceToTema: 290000,
    pricingBreakdown: {
      vehicleAndShipping: 290000,
      estimatedCustoms: 66000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 369000,
    },
    availability: 'in_transit',
    origin: 'chinese_import',
    location: 'Vessel PACIFIC TRADER',
    etaWeeks: 'Arriving in 12 days',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 0,
    engine: 'Blue Whale 2.0T + Aisin 8AT (233 HP)',
    driveType: 'AWD',
    color: 'Carbon Obsidian Black',
    interiorColor: 'Aerospace Black & Copper',
    seats: 5,
    images: [
      '/cars/changan-unik.jpg',
      '/cars/changan-unik-2.jpg',
      '/cars/changan-unik-3.jpg',
      '/cars/changan-unik-4.jpg',
      '/cars/changan-unik-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema Port / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      'Borderless Diamond Grille',
      'Sony Headrest Audio Speakers',
      'Quad Exhaust Pipes with Rear Diffuser',
      'Level 2.5 Autonomous Pilot'
    ],
    description: 'Changan’s flagship luxury crossover. Known for its Porsche Cayenne silhouette, serene acoustic cabin, and smooth Aisin 8-speed transmission.',
    isFeatured: true,
  },
  {
    id: 'changan-uniz-2025',
    slug: 'changan-uni-z-phev-2025',
    make: 'Changan',
    model: 'UNI-Z',
    year: 2025,
    badge: 'Blue Whale iDD PHEV',
    vin: 'LS5AB20D4R0072044',
    priceToTema: 230000,
    pricingBreakdown: {
      vehicleAndShipping: 230000,
      estimatedCustoms: 52000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 295000,
    },
    availability: 'available_china',
    origin: 'chinese_import',
    location: 'Chongqing Vehicle Hub, China',
    etaWeeks: '7-9 weeks to Tema Port',
    bodyType: 'SUV',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    mileage: 0,
    engine: '1.5L Dedicated Hybrid Engine + Electric Motor',
    rangeKm: 1200,
    batteryKwh: 18.4,
    driveType: 'FWD',
    color: 'Starlight Silver',
    interiorColor: 'Warm Camel Leather',
    seats: 5,
    images: [
      '/cars/changan-uniz.jpg',
      '/cars/changan-uniz-2.jpg',
      '/cars/changan-uniz-3.jpg',
      '/cars/changan-uniz-4.jpg',
      '/cars/changan-uniz-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema Port / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      '125 km Pure Electric Range',
      'Dual Screen Digital Command Center',
      'Ultra-Fast DC Fast Charging',
      'Face Recognition Keyless Entry'
    ],
    description: 'Changan’s brand new plug-in hybrid SUV. 125 km pure electric city commuting and over 1,200 km combined fuel economy.',
    isFeatured: false,
  },
  {
    id: 'changan-univ-2025',
    slug: 'changan-uni-v-sport-saloon-2025',
    make: 'Changan',
    model: 'UNI-V',
    year: 2025,
    badge: 'Sport Saloon',
    vin: 'LS5AB20D4R0093811',
    priceToTema: 195000,
    pricingBreakdown: {
      vehicleAndShipping: 195000,
      estimatedCustoms: 44000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 252000,
    },
    availability: 'available_china',
    origin: 'chinese_import',
    location: 'Ningbo Port Depot, China',
    etaWeeks: '7-9 weeks to Tema Port',
    bodyType: 'Saloon',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 0,
    engine: '1.5T Turbo Blue Whale (188 HP)',
    driveType: 'FWD',
    color: 'Nardo Grey',
    interiorColor: 'Orange & Black Sports Bucket Seats',
    seats: 5,
    images: [
      '/cars/changan-univ.jpg',
      '/cars/changan-univ-2.jpg',
      '/cars/changan-univ-3.jpg',
      '/cars/changan-univ-4.jpg',
      '/cars/changan-univ-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema Port / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      'Electric Retractable Rear Wing Spoiler',
      'Active Sport Exhaust Valve Mode',
      'Fastback Coupe Saloon Silhouette',
      'Formula-Style Flat Bottom Steering Wheel'
    ],
    description: 'An aggressive, high-tech sports saloon car featuring an authentic deployable electric rear spoiler and sport exhaust sound.',
    isFeatured: true,
  },

  // ==========================================
  // 3. BYD LINEUP (Song Plus, Seal, Dolphin)
  // ==========================================
  {
    id: 'byd-song-plus-2026',
    slug: 'byd-song-plus-2026-dmi',
    make: 'BYD',
    model: 'Song Plus DM-i',
    year: 2026,
    badge: 'Honor Edition',
    vin: 'LGXCE43B6R0188921',
    priceToTema: 240000,
    pricingBreakdown: {
      vehicleAndShipping: 240000,
      estimatedCustoms: 55000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 308000,
    },
    availability: 'available_china',
    origin: 'chinese_import',
    location: 'Shenzhen Logistics Hub, China',
    etaWeeks: '7-9 weeks to Tema Port',
    bodyType: 'SUV',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    mileage: 0,
    engine: '1.5L DM-i Plug-in Hybrid',
    rangeKm: 1200,
    batteryKwh: 18.3,
    driveType: 'FWD',
    color: 'Snow White Metallic',
    interiorColor: 'Eclipse Grey & Chestnut',
    seats: 5,
    images: [
      '/cars/byd-song-plus.jpg',
      '/cars/byd-song-plus-2.jpg',
      '/cars/byd-song-plus-3.jpg',
      '/cars/byd-song-plus-4.jpg',
      '/cars/byd-song-plus-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      'DiPilot L2 Driver Assist',
      'Panoramic Sunroof',
      '15.6-inch Rotating Touchscreen',
      '360° HD Panoramic Camera',
      'Vehicle-to-Load (V2L) Power Outlet'
    ],
    description: 'The global benchmark plug-in hybrid SUV. Unrivaled fuel efficiency, ultra-smooth electric propulsion, and factory warranty.',
    isFeatured: true,
  },
  {
    id: 'byd-seal-2025',
    slug: 'byd-seal-ev-2025-awd',
    make: 'BYD',
    model: 'Seal EV Excellence',
    year: 2025,
    badge: 'AWD Performance',
    vin: 'LGXCF54C9S0294118',
    priceToTema: 310000,
    pricingBreakdown: {
      vehicleAndShipping: 310000,
      estimatedCustoms: 62000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 385000,
    },
    availability: 'in_transit',
    origin: 'chinese_import',
    location: 'Vessel MSC LORETTO (En route to Tema)',
    etaWeeks: 'Arriving in 14 days',
    bodyType: 'Saloon',
    fuelType: 'Electric',
    transmission: 'Automatic',
    mileage: 0,
    engine: 'Dual Motor AWD (523 HP)',
    rangeKm: 570,
    batteryKwh: 82.5,
    driveType: 'AWD',
    color: 'Atlantis Grey',
    interiorColor: 'Tahiti Blue Leather',
    seats: 5,
    images: [
      '/cars/byd-seal.jpg',
      '/cars/byd-seal-2.jpg',
      '/cars/byd-seal-3.jpg',
      '/cars/byd-seal-4.jpg',
      '/cars/byd-seal-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      '0-100 km/h in 3.8s',
      'Blade Battery Cell-to-Body Technology',
      'Head-Up Display (HUD)',
      'Dynaudio 12-Speaker Sound System'
    ],
    description: 'High performance sports electric saloon with 570 km range and 523 horsepower. Approaching Gulf of Guinea.',
    isFeatured: false,
  },
  {
    id: 'byd-dolphin-2025',
    slug: 'byd-dolphin-ev-2025',
    make: 'BYD',
    model: 'Dolphin EV',
    year: 2025,
    badge: 'Plus Edition',
    vin: 'LGXCF44B2R0028192',
    priceToTema: 175000,
    pricingBreakdown: {
      vehicleAndShipping: 175000,
      estimatedCustoms: 38000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 226000,
    },
    availability: 'available_china',
    origin: 'chinese_import',
    location: 'Guangzhou Port Vehicle Depot, China',
    etaWeeks: '7-9 weeks to Tema Port',
    bodyType: 'Hatchback',
    fuelType: 'Electric',
    transmission: 'Automatic',
    mileage: 0,
    engine: 'Permanent Magnet Synchronous EV Motor',
    rangeKm: 420,
    batteryKwh: 44.9,
    driveType: 'FWD',
    color: 'Coral Pink & Surf Grey',
    interiorColor: 'Bicolor Sport Fabric',
    seats: 5,
    images: [
      '/cars/byd-dolphin.jpg',
      '/cars/byd-dolphin-2.jpg',
      '/cars/byd-dolphin-3.jpg',
      '/cars/byd-dolphin-4.jpg',
      '/cars/byd-dolphin-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      'Compact City Friendly Dimensions',
      '420 km EV Range (Zero Fuel Costs)',
      'Rotating Center Touchscreen',
      'Blade Battery Safety Pack'
    ],
    description: 'Modern, ultra-efficient small electric city hatchback. Perfect for city driving in Accra and Kumasi with zero emissions and low running costs.',
    isFeatured: false,
  },

  // ==========================================
  // 4. TOYOTA LINEUP (Vitz, Camry, RAV4, Prado, Hilux)
  // ==========================================
  {
    id: 'toyota-vitz-2022',
    slug: 'toyota-vitz-13l-compact-2022',
    make: 'Toyota',
    model: 'Vitz (Yaris)',
    year: 2022,
    badge: 'F-Package 1.3L',
    vin: 'KSP130-2098411',
    priceToTema: 115000,
    pricingBreakdown: {
      vehicleAndShipping: 115000,
      estimatedCustoms: 0, // In Ghana, Duty Paid
      clearingFee: 0,
      dvlaFee: 3500,
      deliveryFee: 1000,
      estimatedRoadReady: 119500,
    },
    availability: 'available_ghana',
    origin: 'local_ghana',
    location: 'Accra Mall Auto Yard, Tetteh Quarshie',
    etaWeeks: 'Immediate Handover (Ghana Registered)',
    bodyType: 'Hatchback',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 28000,
    engine: '1.3L VVT-i 4-Cylinder (Ultra Economical)',
    driveType: 'FWD',
    color: 'Silver Metallic',
    interiorColor: 'Grey Cloth',
    seats: 5,
    images: [
      '/cars/toyota-vitz.jpg',
      '/cars/toyota-vitz-2.jpg',
      '/cars/toyota-vitz-3.jpg',
      '/cars/toyota-vitz-4.jpg',
      '/cars/toyota-vitz-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'East Legon, Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Fuel Economy: 19 km/Litre',
      'Compact Parking Dimensions',
      'Cold Dual Air Conditioning',
      'Touchscreen Infotainment with Bluetooth'
    ],
    description: 'Ghana’s undisputed everyday champion. Unbeatable reliability, cheap spare parts, easy parking in traffic, and ideal for daily commuting or ride-hailing business.',
    isFeatured: true,
  },
  {
    id: 'toyota-camry-2023',
    slug: 'toyota-camry-25-se-2023',
    make: 'Toyota',
    model: 'Camry',
    year: 2023,
    badge: 'SE Sport Edition',
    vin: '4T1B11HK7PU591823',
    priceToTema: 285000,
    pricingBreakdown: {
      vehicleAndShipping: 285000,
      estimatedCustoms: 0, // Cleared in Ghana
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 291000,
    },
    availability: 'available_ghana',
    origin: 'american_global',
    location: 'Spintex Road Showroom, Accra',
    etaWeeks: 'Immediate Handover',
    bodyType: 'Saloon',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 19500,
    engine: '2.5L Dynamic Force 4-Cylinder (203 HP)',
    driveType: 'FWD',
    color: 'Midnight Black Metallic',
    interiorColor: 'Black SofTex Leather',
    seats: 5,
    images: [
      '/cars/toyota-camry.jpg',
      '/cars/toyota-camry-2.jpg',
      '/cars/toyota-camry-3.jpg',
      '/cars/toyota-camry-4.jpg',
      '/cars/toyota-camry-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'Spintex, Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Toyota Safety Sense 2.5+',
      '18-inch Black Machined Wheels',
      'Apple CarPlay & Android Auto',
      'Sport Tuned Suspension'
    ],
    description: 'The executive saloon standard in Ghana. Impeccable highway comfort, prestigious appearance, and bulletproof Toyota mechanicals.',
    isFeatured: false,
  },
  {
    id: 'toyota-rav4-2024',
    slug: 'toyota-rav4-hybrid-awd-2024',
    make: 'Toyota',
    model: 'RAV4',
    year: 2024,
    badge: 'XLE Hybrid AWD',
    vin: '2T3P1RFV5RW198421',
    priceToTema: 380000,
    pricingBreakdown: {
      vehicleAndShipping: 380000,
      estimatedCustoms: 0, // Cleared in Ghana
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 386000,
    },
    availability: 'available_ghana',
    origin: 'american_global',
    location: 'Apex Motors Showroom, East Legon, Accra',
    etaWeeks: 'Immediate Handover',
    bodyType: 'SUV',
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    mileage: 6200,
    engine: '2.5L Hybrid Electronic AWD',
    driveType: 'AWD',
    color: 'Magnetic Grey Metallic',
    interiorColor: 'Ash Grey Leather',
    seats: 5,
    images: [
      '/cars/toyota-rav4.jpg',
      '/cars/toyota-rav4-2.jpg',
      '/cars/toyota-rav4-3.jpg',
      '/cars/toyota-rav4-4.jpg',
      '/cars/toyota-rav4-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'East Legon, Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Electronic On-Demand All-Wheel Drive',
      'Blind Spot Monitor with Rear Cross-Traffic Alert',
      'Power Moonroof',
      'LED Projector Headlights'
    ],
    description: 'Ghana’s favorite compact SUV. Exceptional hybrid gas mileage, elevated road clearance, and unmatched resale value in Accra.',
    isFeatured: true,
  },
  {
    id: 'toyota-prado-2024',
    slug: 'toyota-land-cruiser-prado-2024',
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    year: 2024,
    badge: 'TX-L 7-Seater',
    vin: 'JTEBU5JR1P5099812',
    priceToTema: 980000,
    pricingBreakdown: {
      vehicleAndShipping: 980000,
      estimatedCustoms: 0,
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 986000,
    },
    availability: 'available_ghana',
    origin: 'local_ghana',
    location: 'East Legon Showroom, Accra',
    etaWeeks: 'Immediate Delivery (Registered/Clearing Paid)',
    bodyType: 'SUV',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    mileage: 4200,
    engine: '2.8L D-4D Turbo Diesel',
    driveType: '4WD',
    color: 'Pearl White Crystal',
    interiorColor: 'Beige Leather',
    seats: 7,
    images: [
      '/cars/toyota-prado.jpg',
      '/cars/toyota-prado-2.jpg',
      '/cars/toyota-prado-3.jpg',
      '/cars/toyota-prado-4.jpg',
      '/cars/toyota-prado-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'East Legon, Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Full-Time 4WD with Multi-Terrain Select',
      'Cool Box Refrigerator in Console',
      'Kinetic Dynamic Suspension (KDSS)',
      'Apple CarPlay & Keyless Entry'
    ],
    description: 'Fully cleared, duty-paid pristine Toyota Land Cruiser Prado TX-L ready for physical test drive and instant handover in East Legon.',
    isFeatured: true,
  },
  {
    id: 'toyota-hilux-2024',
    slug: 'toyota-hilux-double-cabin-2024',
    make: 'Toyota',
    model: 'Hilux',
    year: 2024,
    badge: 'Revo Rocco 4x4',
    vin: 'MR0HA3CD8P0041289',
    priceToTema: 450000,
    pricingBreakdown: {
      vehicleAndShipping: 450000,
      estimatedCustoms: 88000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 551000,
    },
    availability: 'in_transit',
    origin: 'american_global',
    location: 'Vessel CMA CGM DAKAR',
    etaWeeks: 'Arriving in 18 days',
    bodyType: 'Pickup',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    mileage: 0,
    engine: '2.8L GD-6 Turbo Diesel (204 HP / 500 Nm)',
    driveType: '4WD',
    color: 'Crimson Spark Red',
    interiorColor: 'Black Rocco Leather',
    seats: 5,
    images: [
      '/cars/toyota-hilux.jpg',
      '/cars/toyota-hilux-2.jpg',
      '/cars/toyota-hilux-3.jpg',
      '/cars/toyota-hilux-4.jpg',
      '/cars/toyota-hilux-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      'Heavy-Duty Commercial Payload & Towing',
      'Rear Differential Lock',
      'Bedliner with Roll Bar Sports Pack',
      'High Ground Clearance 286mm'
    ],
    description: 'The king of African roads. Tough double-cabin pickup truck built for heavy mining, agricultural, and executive transport across Ghana.',
    isFeatured: false,
  },

  // ==========================================
  // 5. HONDA LINEUP (Civic, Accord, CR-V)
  // ==========================================
  {
    id: 'honda-civic-2023',
    slug: 'honda-civic-15t-sport-2023',
    make: 'Honda',
    model: 'Civic',
    year: 2023,
    badge: 'Sport Saloon',
    vin: '19XFL1H87PE018442',
    priceToTema: 220000,
    pricingBreakdown: {
      vehicleAndShipping: 220000,
      estimatedCustoms: 0, // Cleared in Ghana
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 226000,
    },
    availability: 'available_ghana',
    origin: 'american_global',
    location: 'Airport Residential Showroom, Accra',
    etaWeeks: 'Immediate Handover',
    bodyType: 'Saloon',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 18400,
    engine: '1.5L Turbo VTEC (180 HP)',
    driveType: 'FWD',
    color: 'Sonic Grey Pearl',
    interiorColor: 'Black Sport Trim',
    seats: 5,
    images: [
      '/cars/honda-civic.jpg',
      '/cars/honda-civic-2.jpg',
      '/cars/honda-civic-3.jpg',
      '/cars/honda-civic-4.jpg',
      '/cars/honda-civic-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'Airport Residential, Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Honda Sensing Suite (Adaptive Cruise, Lane Keep)',
      'Sport Pedals & Paddle Shifters',
      'Honeycomb Grille Dashboard',
      'Bose Premium Sound'
    ],
    description: 'Youthful, sharp handling sports saloon. Excellent fuel efficiency, modern interior design, and agile driving dynamics.',
    isFeatured: false,
  },
  {
    id: 'honda-accord-2024',
    slug: 'honda-accord-touring-2024',
    make: 'Honda',
    model: 'Accord',
    year: 2024,
    badge: 'Touring Edition',
    vin: '1HGCY1F87RA049102',
    priceToTema: 320000,
    pricingBreakdown: {
      vehicleAndShipping: 320000,
      estimatedCustoms: 0,
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 326000,
    },
    availability: 'available_ghana',
    origin: 'american_global',
    location: 'Spintex Road Yard, Accra',
    etaWeeks: 'Immediate Handover',
    bodyType: 'Saloon',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 8500,
    engine: '1.5T VTEC Turbo Engine',
    driveType: 'FWD',
    color: 'Platinum White Pearl',
    interiorColor: 'Perforated Leather',
    seats: 5,
    images: [
      '/cars/honda-accord.jpg',
      '/cars/honda-accord-2.jpg',
      '/cars/honda-accord-3.jpg',
      '/cars/honda-accord-4.jpg',
      '/cars/honda-accord-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'Spintex, Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Google Built-in Operating System',
      'Head-Up Display & Wireless Charging',
      'Ventilated Front Seats',
      '12.3-inch Center Touchscreen'
    ],
    description: 'Executive luxury saloon with flagship comfort, acoustic glass, and prestigious presence for Ghanaian executives.',
    isFeatured: false,
  },
  {
    id: 'honda-crv-2024',
    slug: 'honda-crv-exl-awd-2024',
    make: 'Honda',
    model: 'CR-V',
    year: 2024,
    badge: 'EX-L AWD',
    vin: '7FARW1H87RE011924',
    priceToTema: 360000,
    pricingBreakdown: {
      vehicleAndShipping: 360000,
      estimatedCustoms: 0,
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 366000,
    },
    availability: 'available_ghana',
    origin: 'american_global',
    location: 'East Legon Showroom, Accra',
    etaWeeks: 'Immediate Handover',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 7200,
    engine: '1.5T Turbocharged AWD',
    driveType: 'AWD',
    color: 'Canyon River Blue',
    interiorColor: 'Grey Leather',
    seats: 5,
    images: [
      '/cars/honda-crv.jpg',
      '/cars/honda-crv-2.jpg',
      '/cars/honda-crv-3.jpg',
      '/cars/honda-crv-4.jpg',
      '/cars/honda-crv-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'East Legon, Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Real Time AWD with Intelligent Control',
      'Power Tailgate with Hands-Free Access',
      'Wireless Apple CarPlay / Android Auto',
      'Generous Cargo Boot Space'
    ],
    description: 'Renowned family SUV combining cavernous boot space, outstanding crash safety ratings, and smooth city driving.',
    isFeatured: true,
  },

  // ==========================================
  // 6. HYUNDAI LINEUP (Elantra, Tucson)
  // ==========================================
  {
    id: 'hyundai-elantra-2024',
    slug: 'hyundai-elantra-limited-2024',
    make: 'Hyundai',
    model: 'Elantra',
    year: 2024,
    badge: 'Limited Edition',
    vin: 'KMHD84LF7RU189421',
    priceToTema: 210000,
    pricingBreakdown: {
      vehicleAndShipping: 210000,
      estimatedCustoms: 0,
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 216000,
    },
    availability: 'available_ghana',
    origin: 'american_global',
    location: 'Cantonments Auto Gallery, Accra',
    etaWeeks: 'Immediate Handover',
    bodyType: 'Saloon',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 12000,
    engine: '2.0L Smartstream 4-Cylinder',
    driveType: 'FWD',
    color: 'Intense Blue Metallic',
    interiorColor: 'Melange Grey Leather',
    seats: 5,
    images: [
      '/cars/hyundai-elantra.jpg',
      '/cars/hyundai-elantra-2.jpg',
      '/cars/hyundai-elantra-3.jpg',
      '/cars/hyundai-elantra-4.jpg',
      '/cars/hyundai-elantra-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'Cantonments, Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Parametric Jewel Surface Bodywork',
      'Dual 10.25-inch High-Res Displays',
      'Smart Cruise Control with Stop & Go',
      'Heated Front Seats'
    ],
    description: 'Chiseled modern saloon car with spaceship interior design and low maintenance costs across Ghana.',
    isFeatured: false,
  },
  {
    id: 'hyundai-tucson-2024',
    slug: 'hyundai-tucson-nline-2024',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2024,
    badge: 'N-Line Sport',
    vin: 'KM8JB3A41RU209144',
    priceToTema: 340000,
    pricingBreakdown: {
      vehicleAndShipping: 340000,
      estimatedCustoms: 0,
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 346000,
    },
    availability: 'available_ghana',
    origin: 'american_global',
    location: 'Tema Motorway Auto Hub, Greater Accra',
    etaWeeks: 'Immediate Handover',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 9400,
    engine: '1.6T Smartstream Turbocharged (187 HP)',
    driveType: 'AWD',
    color: 'Titan Grey Matte',
    interiorColor: 'N-Line Suede & Leather',
    seats: 5,
    images: [
      '/cars/hyundai-tucson.jpg',
      '/cars/hyundai-tucson-2.jpg',
      '/cars/hyundai-tucson-3.jpg',
      '/cars/hyundai-tucson-4.jpg',
      '/cars/hyundai-tucson-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'Tema, Greater Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Parametric Hidden DRL Headlights',
      'HTRAC All-Wheel Drive with Snow/Mud Modes',
      'Bose 8-Speaker Audio System',
      'Shift-by-Wire Push Button Gear Selector'
    ],
    description: 'Sporty N-Line package with aerodynamic styling, firm suspension tuning, and high ground clearance.',
    isFeatured: false,
  },

  // ==========================================
  // 7. AMERICAN PICKUP (Ford Ranger Wildtrak)
  // ==========================================
  {
    id: 'ford-ranger-2024',
    slug: 'ford-ranger-wildtrak-4x4-2024',
    make: 'Ford',
    model: 'Ranger',
    year: 2024,
    badge: 'Wildtrak Bi-Turbo',
    vin: '1FTFW1E84PKD01948',
    priceToTema: 420000,
    pricingBreakdown: {
      vehicleAndShipping: 420000,
      estimatedCustoms: 85000,
      clearingFee: 7000,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 518000,
    },
    availability: 'in_transit',
    origin: 'american_global',
    location: 'Vessel PACIFIC TRADER',
    etaWeeks: 'Arriving in 14 days',
    bodyType: 'Pickup',
    fuelType: 'Diesel',
    transmission: 'Automatic',
    mileage: 0,
    engine: '2.0L Bi-Turbo Diesel (210 HP / 500 Nm)',
    driveType: '4WD',
    color: 'Cyber Orange Metallic',
    interiorColor: 'Wildtrak Leather with Orange Stitching',
    seats: 5,
    images: [
      '/cars/ford-ranger.jpg',
      '/cars/ford-ranger-2.jpg',
      '/cars/ford-ranger-3.jpg',
      '/cars/ford-ranger-4.jpg',
      '/cars/ford-ranger-5.jpg'
    ],
    seller: {
      id: 'agorazo-direct',
      name: 'Agorazo Direct (Verified Supplier)',
      type: 'Agorazo Direct',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      location: 'Tema / Cantonments, Accra',
      phone: '+233 24 000 1234',
      whatsapp: '+233 24 000 1234',
    },
    features: [
      '12-inch SYNC 4A Vertical Touchscreen',
      'Matrix LED Headlamps',
      'Integrated Rear Box Step & Cargo Management',
      'Zone Lighting for Night Operations'
    ],
    description: 'American high-spec luxury pickup truck. 3,500 kg towing capacity, advanced 4WD drive modes, and executive cab refinement.',
    isFeatured: true,
  },

  // ==========================================
  // 8. GEELY MONJARO (Flagship Chinese SUV)
  // ==========================================
  {
    id: 'geely-monjaro-2024',
    slug: 'geely-monjaro-awd-2024',
    make: 'Geely',
    model: 'Monjaro (Xingyue L)',
    year: 2024,
    badge: 'Executive AWD',
    vin: 'LB37648B1P0028441',
    priceToTema: 295000,
    pricingBreakdown: {
      vehicleAndShipping: 295000,
      estimatedCustoms: 0,
      clearingFee: 0,
      dvlaFee: 4500,
      deliveryFee: 1500,
      estimatedRoadReady: 301000,
    },
    availability: 'available_ghana',
    origin: 'chinese_import',
    location: 'Tema Bonded Yard, Ghana',
    etaWeeks: 'Immediate Handover',
    bodyType: 'SUV',
    fuelType: 'Petrol',
    transmission: 'Automatic',
    mileage: 1800,
    engine: '2.0T Drive-E Volvo Engine (238 HP)',
    driveType: 'AWD',
    color: 'Emerald Shadow Green',
    interiorColor: 'Cognac Suede',
    seats: 5,
    images: [
      '/cars/geely-monjaro.jpg',
      '/cars/geely-monjaro-2.jpg',
      '/cars/geely-monjaro-3.jpg',
      '/cars/geely-monjaro-4.jpg',
      '/cars/geely-monjaro-5.jpg'
    ],
    seller: {
      id: 'apex-motors',
      name: 'Apex Motors Ghana',
      type: 'Verified Dealer',
      isVerified: true,
      rating: 4.8,
      reviewCount: 88,
      location: 'Tema Motorway, Greater Accra',
      phone: '+233 20 111 8899',
      whatsapp: '+233 20 111 8899',
    },
    features: [
      'Triple Full-Width Dashboard Screens',
      'Bose Sound System with Active Noise Cancellation',
      'Panoramic Sunroof',
      'Volvo CMA Platform Architecture'
    ],
    description: 'Built on the award-winning CMA platform developed with Volvo. Exceptional ride refinement, premium materials, and instant availability in Tema.',
    isFeatured: false,
  }
];

export const INITIAL_ACTIVE_ORDER: Order = {
  id: 'order-ag-001',
  orderNumber: 'AG-2026-000241',
  vehicle: INITIAL_VEHICLES[0], // Jetour T2
  totalAmount: 428000,
  amountPaid: 128400, // 30% Down payment made
  balanceDue: 299600,
  services: {
    clearing: true,
    dvla: true,
    insurance: false,
    delivery: true,
  },
  paymentPlan: {
    id: 'plan-30-40-30',
    name: '30 / 40 / 30 Milestone Import Plan',
    description: '30% deposit to secure vehicle and factory export, 40% before ship departure, 30% upon arrival at Tema Port.',
    type: 'milestones',
    milestones: [
      {
        id: 'm-1',
        milestoneNumber: 1,
        title: 'Initial Deposit & Order Allocation',
        percentage: 30,
        amount: 128400,
        triggerEvent: 'Order Placement',
        status: 'paid',
        paidAt: '28 Aug 2026',
        paymentMethod: 'MTN Mobile Money (*170#)',
      },
      {
        id: 'm-2',
        milestoneNumber: 2,
        title: 'Pre-Shipment & Bill of Lading Issuance',
        percentage: 40,
        amount: 171200,
        triggerEvent: 'Before Vessel Departure',
        status: 'due',
        dueDate: '15 Sep 2026',
      },
      {
        id: 'm-3',
        milestoneNumber: 3,
        title: 'Tema Port Arrival & Customs Clearance',
        percentage: 30,
        amount: 128400,
        triggerEvent: 'Vessel Arrival at Tema Port',
        status: 'upcoming',
        dueDate: '18 Oct 2026',
      }
    ]
  },
  status: 'at_sea',
  shippingInfo: {
    vesselName: 'PACIFIC TRADER',
    voyageNumber: 'V.2608W',
    containerNumber: 'MSCU8942109',
    billOfLadingNumber: 'BL-SZ-TMA-2026-0914',
    departurePort: 'Shenzhen Shekou Port, China',
    departureDate: '02 Sep 2026',
    etaTema: '24 Sep 2026',
    currentCoordinates: { lat: 4.12, lng: -2.85 }
  },
  createdAt: '28 Aug 2026',
  customer: {
    name: 'Emmanuel Mensah',
    phone: '+233 24 456 7890',
    email: 'emmanuel.mensah@gmail.com',
    ghanaPostGps: 'GA-492-1082 (East Legon, Accra)',
    ghanaCardNumber: 'GHA-718293041-9'
  }
};

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    title: 'Proforma Invoice & Purchase Agreement',
    category: 'Purchase',
    fileName: 'Agorazo_Purchase_AG2026000241.pdf',
    fileSize: '412 KB',
    uploadedAt: '28 Aug 2026',
    verified: true,
    downloadUrl: '#',
  },
  {
    id: 'doc-2',
    title: 'Deposit Payment Receipt (30%)',
    category: 'Payments',
    fileName: 'MTN_MoMo_Receipt_GHS128400.pdf',
    fileSize: '185 KB',
    uploadedAt: '28 Aug 2026',
    verified: true,
    downloadUrl: '#',
  },
  {
    id: 'doc-3',
    title: 'Bill of Lading (Ocean Transport)',
    category: 'Shipping',
    fileName: 'Bill_of_Lading_BL_SZ_TMA_2026.pdf',
    fileSize: '1.2 MB',
    uploadedAt: '03 Sep 2026',
    verified: true,
    downloadUrl: '#',
  },
  {
    id: 'doc-4',
    title: 'Manufacturer Certificate of Origin',
    category: 'Customs',
    fileName: 'Jetour_Certificate_Origin_VIN92831.pdf',
    fileSize: '890 KB',
    uploadedAt: '01 Sep 2026',
    verified: true,
    downloadUrl: '#',
  },
  {
    id: 'doc-5',
    title: 'GRA Customs Pre-Assessment Notice',
    category: 'Customs',
    fileName: 'GRA_Duty_Assessment_Draft.pdf',
    fileSize: '340 KB',
    uploadedAt: '04 Sep 2026',
    verified: false,
    downloadUrl: '#',
  }
];

export const INITIAL_QUOTES: QuoteRequest[] = [
  {
    id: 'quote-req-101',
    make: 'Jetour',
    model: 'T2 Traveller 4WD',
    yearMin: 2024,
    yearMax: 2026,
    budgetMin: 320000,
    budgetMax: 360000,
    bodyType: 'SUV',
    fuelType: 'Petrol',
    notes: 'Prefer Sandstone Khaki exterior with tan interior. Need delivery to Kumasi if possible.',
    customerName: 'Emmanuel Mensah',
    customerPhone: '+233 24 456 7890',
    customerEmail: 'emmanuel.mensah@gmail.com',
    status: 'quoted',
    createdAt: '03 Sep 2026',
    receivedQuotesCount: 2,
  }
];

export const INITIAL_LEADS: LeadItem[] = [
  {
    id: 'lead-01',
    customerName: 'Kofi Asante',
    customerPhone: '+233 50 123 4567',
    vehicleInterest: 'Jetour T2 (Traveller) 2025',
    source: 'Marketplace',
    status: 'New',
    createdAt: 'Today, 10:15 AM',
    budget: 340000,
  },
  {
    id: 'lead-02',
    customerName: 'Abena Osei',
    customerPhone: '+233 24 987 6543',
    vehicleInterest: 'Toyota Vitz 1.3L Hatchback',
    source: 'WhatsApp',
    status: 'Quoted',
    createdAt: 'Yesterday, 3:45 PM',
    budget: 115000,
  },
  {
    id: 'lead-03',
    customerName: 'Kwame Boateng',
    customerPhone: '+233 27 345 6789',
    vehicleInterest: 'Changan UNI-K 2.0T AWD',
    source: 'Marketplace',
    status: 'Contacted',
    createdAt: '06 Sep 2026',
    budget: 290000,
  }
];

export const INITIAL_PRICING_RULES = [
  { category: 'SUV', markupPercentage: 9, fixedFee: 0, notes: 'Applies to hybrid, EV, and petrol SUVs (Jetour, Changan, Toyota)' },
  { category: 'Saloon', markupPercentage: 10, fixedFee: 0, notes: 'Executive and sport saloons (Camry, Accord, Civic, UNI-V)' },
  { category: 'Hatchback', markupPercentage: 8, fixedFee: 0, notes: 'Small compact cars & city hatchbacks (Vitz, Dolphin)' },
  { category: 'Pickup', markupPercentage: 0, fixedFee: 28000, notes: 'Fixed commercial utility vehicle markup (Hilux, Ranger)' },
];
